### PR TITLE
Allow extraction from stdin

### PR DESCRIPTION
**Pull request by tpalsulich**
Apache Tika can output structured text for a wide variety of file formats. By allowing `Landmark.py` to take input on stdin, Tika's output can be piped in and filtered:
```
java -jar /path/to/tika-app.jar [filename/url] | python extraction/Landmark.py [options] [rules]
```

Let me know what you think! I'd be happy to iterate.

### CODE REVIEW

**Comment by chrismattmann** [comment]
hi @bamana FYI the attached which would ease integration in one way to Tika. Can you have a look?

**Comment by bamana** [comment]
Looks good to me! Totally willing to iterate more if necessary - anything that will get this integrated with Tika easier.

**Comment by tpalsulich** [comment]
Awesome. Thanks, @bamana!

**Comment by chrismattmann** [comment]
Thank you @bamana !

**Pull request merged**
